### ISSUE TITLE
Getting Fatal error: "Cannot open file <path>Classes/Player.ecl (No such file or directory) ()"

### ISSUE THREAD

**Issue by infapi00** [tx00100xt/SeriousSamClassic-VK#10]
I followed the instructions to build and run from here:

https://github.com/tx00100xt/SeriousSamClassic-VK

But when then I tried to execute it, I got that error. Both on my intel laptop and on the rpi4 (although on the rpi4 I struggled initially to get the error visualized).

It is worth to note that I didn't downloaded the original game resources, as the guide points this:
"This version of the engine comes with a set of resources (\SE1_10b.GRO) that allow you to freely use the engine without any additional resources required."

Opening it doesn't list any ecl file. But the Free XPLUS gro file contains several ecl file. So not sure if this is a problem with the engine itself, or with SE1_10B.gro file.

**Comment by tx00100xt** [comment]
> It is worth to note that I didn't downloaded the original game resources, as the guide points this:
> "This version of the engine comes with a set of resources (\SE1_10b.GRO) that allow you to freely use the engine without any additional resources required."

This mean the engine, not the game itself.
Resources are needed to run the game with this engine:
https://github.com/tx00100xt/SeriousSamClassic-VK#serious-sam-classic-the-first-encounter
https://github.com/tx00100xt/SeriousSamClassic-VK#serious-sam-classic-the-second-encounter
SE1_00_Logo.gro - not needed

**Comment by infapi00** [comment]
> This mean the engine, not the game itself.

Well, but then there is no instructions of how to run just the engine. Or in other words, what I really can do with SE1_10b.GRO?

> Resources are needed to run the game with this engine:

Ok, thanks for the clarification. Will try to get those resources somehow.

**Comment by tx00100xt** [comment]
You can build a free demo using the following script. After the building is finished, you can immediately start the game.
>#!/bin/bash
git clone https://github.com/tx00100xt/SeriousSamClassic-VK.git
cd SeriousSamClassic-VK/SamTFE
wget https://archive.org/download/SeriousSamDemo/SeriousSamDemo.exe
wget http://www.cngwireless.net/apps/Game%20Patches/serioussampatch105_usa.exe
7z x SeriousSamDemo.exe
7z x -y serioussampatch105_usa.exe
cp -vr Disk1/* .
sed -i 's/01_Hatshepsut.wld/KarnakDemo.wld/g' Sources/SeriousSam/SeriousSam.cpp
sed -i 's/sam_menulogo256a.tex/sam_menulogo256a_demo.tex/g' Sources/SeriousSam/Menu.cpp
sed -i 's/sam_menulogo256b.tex/sam_menulogo256b_demo.tex/g' Sources/SeriousSam/Menu.cpp
cd Sources
./build-linux64.sh -DTFE=TRUE
>
>cd ..
cd ..
cd SamTSE
wget https://www.massassi.net/files/serious/serioussamsedemo.exe
wget http://www.cngwireless.net/apps/Game%20Patches/secondencounterpatch107_usa.exe
7z x serioussamsedemo.exe
7z x -y secondencounterpatch107_usa.exe
cp -vr Disk1/* .
sed -i 's/1_0_InTheLastEpisode.wld/Demo\\\\Palenque_Demo.wld/g' Scripts/Game_startup.ini
sed -i 's/1_0_InTheLastEpisode.wld/Demo\\\\Palenque_Demo.wld/g' Sources/SeriousSam/SeriousSam.cpp
sed -i 's/sam_menulogo256a.tex/sam_menulogo256a_demo.tex/g' Sources/SeriousSam/Menu.cpp
sed -i 's/sam_menulogo256b.tex/sam_menulogo256b_demo.tex/g' Sources/SeriousSam/Menu.cpp
cd Sources
./build-linux64.sh
>
[build-linux64demo.sh.txt](https://github.com/tx00100xt/SeriousSamClassic-VK/files/9276943/build-linux64demo.sh.txt)

**Comment by infapi00** [comment]
Interesting, thanks for the suggestion. Perhaps could be worth to include on the repository?

FWOW, I was able to get a copy of the TSE, but I would go back to your script if I need more testing.

In any case, I will close this issue, as the guide properly points that to run the game, you need resources not included with the repository. Thanks for the help.
