### ISSUE TITLE
RPi4 - Segmentation Fault

### ISSUE THREAD

**Issue by dragon99919** [tx00100xt/SeriousSamClassic-VK#13]
Hey again! : D
So, while now the code compiles indeed, today I had a chance to try to run it, and for both FE and SE I got this message:

> dragon99919@marcinek-rpi4-vanilla-sandbox:~/git/SeriousSamClassic-VK/SamTFE/Bin $ ./SeriousSam
> STUBBED: load window icon in /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/Sources/SeriousSam/MainWindow.cpp, line 172.
> STUBBED: Need SDL invisible window or something in /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/Sources/SeriousSam/MainWindow.cpp, line 353.
> Segmentation fault
> dragon99919@marcinek-rpi4-vanilla-sandbox:~/git/SeriousSamClassic-VK/SamTFE/Bin $ 

I tried to add original FE and SE gro files to their directories - nothing changed.

**Comment by tx00100xt** [comment]
You can try changing the line
https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/SamTFE/Sources/CMakeLists.txt#L314

>option(USE_SINGLE_THREAD "Use Single Threaded version" FALSE)
>
To
>
>option(USE_SINGLE_THREAD "Use Single Threaded version" TRUE)
>
Rebuild and try to run again
Without debugger output, it's hard to guess anything.
As far as I know the 64-bit version works under RPI4.

**Comment by dragon99919** [comment]
Sadly, no difference with that line changed. : /

**Comment by tx00100xt** [comment]
Segmentation Fault can also occur when certain game resources are missing. Please attach the game log.
>~/./.local/share/Serious-Engine/serioussam/SeriousSam.log
>~/./.local/share/Serious-Engine/serioussamse/SeriousSam.log
>

**Comment by dragon99919** [comment]
There they are:

FE:
> --- Serious Engine Startup ---
>   SeriousEngine Build: 10000.10
> 
> Running 32-bit version
> Executable: /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/Bin/
> Assumed engine data directory: /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/
> Assumed mods library directory: /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/
> 
> Examining underlying OS...
>   Type: Unix
> 
> Detecting CPU...
>   (No CPU detection in this binary.)
> 
> Cannot load variable from 'DefaultMod.txt':
> Cannot open file `/home/dragon99919/git/SeriousSamClassic-VK/SamTFE/DefaultMod.txt' (No such file or directory) ()
> Current mod: <none>
> Loading group files...
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/SE1_10b.gro: 105 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/1_04_patch.gro: 1 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/1_00c_scripts.gro: 28 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/1_00c_Logo.gro: 1 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/1_00c.gro: 2267 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/1_00_music.gro: 55 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTFE/1_00_ExtraTools.gro: 58 files
> 
> Detecting input devices...
>   joysticks found: 0
>   joysticks allowed: 0
> 
> 
> GfxLibrary: InitAPI
> GfxLibrary: OpenGL InitAPIs.
> GfxLibrary: Vulkan InitAPIs.
> 

TSE:

> --- Serious Engine Startup ---
>   SeriousEngine Build: 10000.10
> 
> Running 32-bit version
> Executable: /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/Bin/
> Assumed engine data directory: /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/
> Assumed mods library directory: /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/
> 
> Examining underlying OS...
>   Type: Unix
> 
> Detecting CPU...
>   (No CPU detection in this binary.)
> 
> Cannot load variable from 'DefaultMod.txt':
> Cannot open file `/home/dragon99919/git/SeriousSamClassic-VK/SamTSE/DefaultMod.txt' (No such file or directory) ()
> Current mod: <none>
> Loading group files...
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/SE1_10b.gro: 105 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/SE1_00_Music.gro: 43 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/SE1_00_Logo.gro: 1 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/SE1_00_Levels.gro: 49 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/SE1_00_ExtraTools.gro: 1044 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/SE1_00_Extra.gro: 107 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/SE1_00.gro: 3142 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/1_07_tools.gro: 18 files
>   /home/dragon99919/git/SeriousSamClassic-VK/SamTSE/1_04_patch.gro: 1 files
> 
> Detecting input devices...
>   joysticks found: 0
>   joysticks allowed: 0
> 
> 
> GfxLibrary: InitAPI
> GfxLibrary: OpenGL InitAPIs.
> GfxLibrary: Vulkan InitAPIs.
>

**Comment by dragon99919** [comment]
By the by, I just tried the 64-bit version on aarch64, same thing happening.

**Comment by tx00100xt** [comment]
All the necessary resources are there

Everything worked on raspberry pi 4 Ubuntu 22 lts:
[https://github.com/tx00100xt/SeriousSamClassic-VK/issues/3](https://github.com/tx00100xt/SeriousSamClassic-VK/issues/3)
You can try to roll back to the version - when everything worked exactly.

git clone https://github.com/tx00100xt/SeriousSamClassic-VK.git
cd SeriousSamClassic-VK/SamTFE
git checkout 40bfc9a0cebc5a49a371d99d1164502f2de28b7f

and building game

I would like to look at the output of vulkaninfo. You can attach it to a post.

**Comment by dragon99919** [comment]
And here my dumbness comes clean!
After typing vulkaninfo it showed me that I don't have proper drivers installed. I though Rasperry Pi OS delievers them OOTB, appears I was wrong. Installed these and now all works fine, thanks for the help and sorry for bothering. : )

**Comment by tx00100xt** [comment]
Everything is fine. The main thing is that it worked.
