### ISSUE TITLE
many cvars roll back to his default values when you close/launch the game

### ISSUE THREAD

**Issue by Sol1vaN** [tx00100xt/SeriousSamClassic-VK#14]
Hi there,

I want to change some advanced graphics options but the game always reset the values, here's the list.
I've chequed the PersistentSymbols.ini

tex_iNormalQuality=22 always reset to 0
tex_iAnimationSize=8 always reset to 7
tex_iFiltering=0 always reset to -1
tex_iEffectFiltering=5 always reset to 4
shd_iFiltering=5 always reset to 3
shd_fCacheSize=24 always reset to 16
shd_bCacheAll=1 always reset to 0
mdl_fLODMul=0.5 always reset to 1
mdl_iLODDisappear=0 always reset to 1
mdl_iShadowQuality=3 always reset to 1
gap_iDithering=0 always reset to 2
d3d_iVertexBuffersSize=2048 always reset to 512

*this happens with bot versions of the game, FE and SE.

**Comment by tx00100xt** [comment]
Hello. You are using the Windows or Linux version of the game. Base game or Mod. Please clarify.

**Comment by Sol1vaN** [comment]
Hi! sure.
I'm using Windows version for the base games.
Also the mods suffers the same problems (XPLUS and SSA).

**Comment by tx00100xt** [comment]
When I ported Vulkan support to Linux, I left the void ForceModernHardwareGraphicsSettings() function only for Windows https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/SamTFE/Sources/Engine/Graphics/Gfx_Vulkan.cpp#L149
Then I forgot to kill her call when I added support for windows. Initially, the project was only for *nix systems.
This function resets the parameters.
https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/SamTFE/Sources/Engine/Graphics/GfxLibrary.cpp#L2368

I will remove the call to this function and update the release within two or three days.

**Comment by tx00100xt** [comment]
Removed the function call.
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/0f654779e8a571ce282d40d2379c461ae891322a
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/bd6d5a08305cd5f3b35b74a02b8b53735b977890

**Comment by tx00100xt** [comment]
Updated release:
https://github.com/tx00100xt/SeriousSamClassic-VK/releases/tag/v1.10.4

[SeriousSamClassicVk-1.10.4-win32-bin.zip](https://github.com/tx00100xt/SeriousSamClassic-VK/releases/download/v1.10.4/SeriousSamClassicVk-1.10.4-win32-bin.zip)
[SeriousSamClassicVk-1.10.4-win64-bin.zip](https://github.com/tx00100xt/SeriousSamClassic-VK/releases/download/v1.10.4/SeriousSamClassicVk-1.10.4-win64-bin.zip)

Have a good game

**Comment by Sol1vaN** [comment]
many many thanks for the ultra fast reply and solution!
i've tested the games and mods and now work flaweless😎🤩
