### ISSUE TITLE
what is it NVIDIA vendorID 0x13B5 ??

### ISSUE THREAD

**Issue by Heic0** [tx00100xt/SeriousSamClassic-VK#2]
Engine/Graphics/Adapter.cpp

   switch (properties.vendorID)
    {
    case 0x1002: pda->da_strVendor = "Advanced Micro Devices, Inc."; break;
    case 0x10DE: pda->da_strVendor = "Imagination Technologies"; break;
    case 0x13B5: pda->da_strVendor = "NVIDIA Corporation"; break;
    case 0x5143: pda->da_strVendor = "Qualcomm Technologies, Inc."; break;
    case 0x8086: pda->da_strVendor = "Intel Corporation"; break;
    default: pda->da_strVendor = TRANS("unknown");; break;
    }

**Comment by tx00100xt** [comment]
Yes, this is wrong, Nvidia vendor id 0x10DE

**Comment by tx00100xt** [comment]
Fixed https://github.com/tx00100xt/SeriousSamClassic-VK/commit/9f0d60cc4c810eceb8c3e51a24bbf9f91c5dc083
I think the issue can be closed
