### ISSUE TITLE
Слишком высокая сенса

### ISSUE THREAD

**Issue by SopaDeMacaco-UmaDelicia** [tx00100xt/SeriousSamClassic-VK#24]
День добрый. У игры слишком высокая сенса, даже на 0 играть не очень приятно с мышкой в 800dpi, буквально 10см дают оборот в 360 градусов. Тестировал как в wayland так и в xwayland. Думаю, её стоит подкорректировать. Для примера в overwatch2 для меня удобная сенса 600 из 10000, в apex legends 15 из 200.

**Comment by tx00100xt** [comment]
Привет. У меня с этим всё хорошо. Стоит стандартное значение. Может от моделей мышек зависит.
Отрегулировать под себя всегда можно тут: 

![Снимок экрана в 2023-05-28 14-17-11](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/105300480/b4188111-b8c2-4a1e-a102-2f6923fb6df9)

![Снимок экрана в 2023-05-28 14-17-30](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/105300480/22b25c53-7201-40c0-9946-a57e63275b09)

![Снимок экрана в 2023-05-28 14-17-44](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/105300480/ee15b6ae-bb65-4e66-b66f-ee55b11635bc)

**Comment by SopaDeMacaco-UmaDelicia** [comment]
Я копнул чуть глубже, просто у меня отключена mouse acceleration и эта опция, видимо, странно работает. При её отключении сенса становится очень высокой, хотя mouse acceleration должна делать твою чувствительность нелинейной в зависимости от скорости движений мыши, но в игре я, по крайней мере, плавающей чувствительности не заметил.

**Comment by tx00100xt** [comment]
> TLDR Со включённой mouse acceleration становится играбельно.

Думаю issue можно закрыть.
