### ISSUE TITLE
Как запустить ImGui как у тебя на видео в ютубе?

### ISSUE THREAD

**Issue by KaxelDreamhack123** [tx00100xt/SeriousSamClassic-VK#27]
Я немного потанцевал с бубном, но сейчас игра смогла запуститься с помощью файлов игры от SamTSE. Я хотел бы узнать, как сделать нормальное разрешение игры, поскольку в настройках максимальное для меня 16:10 1680x1500(не точно), а у меня моник 2560x1440, но и так хоть бы как-то, но хотелось еще чтобы видно было фпс с помощью ImGui.
Еще хотел бы узнать, могу ли модифицировать что-либо, например скорость мобов, изменить траекторию полета шаров в связки от скелета и т.д. Просто я пытаюсь создать свою игру from scratch что называется, на вулкане и плюсах(да это жопа), так хотелось бы узнать, как тут все работает и потиху применять полученные знания на примере.

**Comment by tx00100xt** [comment]
Сходство интерфейса ввело в заблуждение). На видео на самом деле Mesa Vulkan Overlay, а не  ImGui. Доступно это только в linux. Достаточно запустить любое Vulkan приложение с нужными параметрами. Например:
```
VK_INSTANCE_LAYERS=VK_LAYER_MESA_overlay VK_LAYER_MESA_OVERLAY_CONFIG=submit,draw,pipeline_graphics,position=top-right,width=300 "./SeriousSam"
```
И будет такой оверлей:
![vulkan](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/105300480/d2138468-a885-44f7-bac7-bdeddad8a85b)

> Я хотел бы узнать, как сделать нормальное разрешение игры, поскольку в настройках максимальное для меня 16:10 1680x1500(не точно), а у меня моник 2560x1440, но и так хоть бы как-то
>
Легко. Нужно прописать в фале **Scripts/Game_startup.ini** строчки:
```
sam_iScreenSizeI=2560;
sam_iScreenSizeJ=1440,;
```
или в файле **PersistentSymbols.ini** заменить на:
```
persistent extern INDEX sam_iScreenSizeI=(INDEX)2560;
persistent extern INDEX sam_iScreenSizeJ=(INDEX)1440,;
```

> Еще хотел бы узнать, могу ли модифицировать что-либо, например скорость мобов, изменить траекторию полета шаров в связки от скелета и т.д.
>
Да. Сразу после выхода игры Croteam выпустила SDK именно для этих целей.
Нужно вносить соответствующие изменения в Entities(EntitiesMP - для TSE) /<нужный файл.es>
Эти моды можно использовать в качестве примера:
https://github.com/tx00100xt/SE1-TFE-PlusPlus
https://github.com/tx00100xt/SE1-TFE-OddWorld
https://github.com/tx00100xt/SE1-ParseError

Помошь по SDK всегда могут оказать тут:
https://www.serioussite.ru/forum/5-447-1
