### ISSUE TITLE
STUBBED: Need SDL invisible window or something in /home/singular/Projects/SeriousSam/SeriousSamClassic-VK/SamTFE/Sources/SeriousSam/MainWindow.cpp, line 357.

### ISSUE THREAD

**Issue by Singular112** [tx00100xt/SeriousSamClassic-VK#28]
Добрый день.

Собрал игру на OrangePI 5, воспользовавшись инструкцией для RaspberryPI.
Все получилось (по крайней мере собралось).

Пытаюсь запустить игру через run_game.sh и получаю ошибку:

`singular@singular-desktop:~/Projects/SeriousSam/SeriousSamClassic-VK$ ./run_game.sh
Running Serious Sam Classic launcher
Running Run Serious Sam TFE Classic (Lock 60fps)
STUBBED: load window icon in /home/singular/Projects/SeriousSam/SeriousSamClassic-VK/SamTFE/Sources/SeriousSam/MainWindow.cpp, line 176.
STUBBED: Need SDL invisible window or something in /home/singular/Projects/SeriousSam/SeriousSamClassic-VK/SamTFE/Sources/SeriousSam/MainWindow.cpp, line 357.
./run_game.sh: line 13: 20029 Aborted                 (core dumped) "./SeriousSam"`

Залез в код MainWindow.cpp. Вижу, что там всего 2 варианта - либо WIN32 сборка, либо заглушка в виде сообщения "Need SDL invisible window or something".

Подскажите, что необходимо модифицировать для полноценного запуска ?

**Comment by Singular112** [comment]
Тут даже больше проблема. Игра при выборе версии Serious Sam The Second Encounter (Lock fps\unlock fps) падает сразу с дампом (coredump).

**Comment by tx00100xt** [comment]
На сообщения **STUBBED:** не стоит обращать внимание.Это просто информационные сообщения не влияющие на что либо, Они есть всегда  Их Гордон расставил как памятку при портировании кода.

Очень мало информации.Остаётся только предполагать.
Первое что необходимо сделать - это убедится в правильной установке Vulkan
Как пример: https://github.com/tx00100xt/SeriousSamClassic-VK/issues/13
Первое - нужно дать команду **vulkaninfo** и посмотреть вывод.
Второе -запустить **vkcube** и убедиться что кубик вращается и всё в порядке.

Если **vulkaninfo** и **vkcube** показали что всё в порядке, то стоит смотреть в сторону флагов компиляции.
Для Orange Pi 5 (чип RK3588S) нужно в:
https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/SamTFE/Sources/CMakeLists.txt#L324
https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/SamTSE/Sources/CMakeLists.txt#L324
выставить нужные флаги.

Опции указаны тут: https://gcc.gnu.org/onlinedocs/gcc/ARM-Options.html

**Comment by Singular112** [comment]
Благодарю за ответы.
Выяснил, что на OrangePi5 нет Vulkan совсем и вряд ли будет.
