### ISSUE TITLE
Vulkan error spam in the rcon console.

### ISSUE THREAD

**Issue by just-thefacts** [tx00100xt/SeriousSamClassic-VK#29]
Randomly, but I'd say 60% of the time, the console will start spamming 'errors', visibly (about 3 or 4 lines of it) without hitting tilde to bring down the console. Once it starts, it never stops, and goes in a rapid stream, until I restart with fingers crossed. Windows and Linux versions (v1.10.5 on an AMD Radeon RX 6600 if it matters). Any ideas? Says the following:

Vulkan: Queue Present KHR swap chain image Done.
Vulkan: Queue Present KHR swap chain image Done.
Vulkan: Queue Present KHR swap chain image Done.
...endlessly

**Comment by tx00100xt** [comment]
This message is not needed in the code, either there should be nothing there, or the procedure for recreating the swapchain.
Try this build for Linux:
* [SeriousSamClassicVk-1.10.5-20230910-lnx-amd64-bin.tar.xz](https://disk.yandex.ru/d/QWgtAISoSlI38A)

**Comment by just-thefacts** [comment]
Played around with 20230910 for 30 minutes or so and could not get it to mess up so far. I'm not sure what triggers it though. Probably making a lot of graphics changes, or certain combinations in the menus? I had also already gotten SeriousSamClassicVk-1.10.5-20230713 windows and linux from the actions pages, and those (only tested linux so far) seem good too. Either way, it has not happened since switching versions so if it is still an issue, it's rare and not a big deal.

Can I make a suggestion for future users? You need a lot more of the original files from CD, Steam, or GOG installs than the .gro files listed in the info here. Controls, Data, Levels, Scripts folders, etc. Basically all of it, or it will error about loading levels, won't F6 save, etc. etc. I had to do a lot of reading the log files to figure out what it was complaining about. Also, since the Linux and Windows BIN folder files are not the same names and the rest are shared, you can make a hybrid Linux and Windows native version all in one! Very cool.

This is an excellent project! Runs so much better than the original CD versions, which are hard to even install and patch up these days. Thanks very much.

**Comment by tx00100xt** [comment]
> I'm not sure what triggers it though
>
This location contains the exception handler **VK_ERROR_OUT_OF_DATE_KHR**
Usually happens after a window resize.
> Either way, it has not happened since switching versions so if it is still an issue, it's rare and not a big deal.
>
As far as I know, this problem occurs in some versions of Nvidia drivers
> I had also already gotten SeriousSamClassicVk-1.10.5-20230713 windows and linux from the actions pages, and those (only tested linux so far) seem good too.
>
Versions n SeriousSamClassicVk-1.10.5-20230713 and release version 1.10.5 are identical. Same files.

I've made the fixes to the repo
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/79d36d8092cf1beb20964b2678d3cc43ddf27b18
Auto builds for Linux and Windows are here:
https://github.com/tx00100xt/SeriousSamClassic-VK/actions/runs/6143435012

> Can I make a suggestion for future users? You need a lot more of the original files from CD, Steam, or GOG installs than the .gro files listed in the info here. Controls, Data, Levels, Scripts folders, etc.
>
When building from source, all these directories are in the repo, and there is no need to add them.
In the release description I added the need to have all the content of the game.
https://github.com/tx00100xt/SeriousSamClassic-VK/releases/tag/v1.10.5

> This is an excellent project!
>
Thanks.
