### ISSUE TITLE
raspberry pi 

### ISSUE THREAD

**Issue by xboxones1** [tx00100xt/SeriousSamClassic-VK#3]
Предложенный патч для raspberry pi никак не повлиял на сборку кода, ошибка в Timer.cpp. Попробовал заменить из репы ptitSeb, версия без вулкана собралась и работает, а вот версия с вулканом собралась, но не работает, ошибка сегментирования.
```
Running Run Serious Sam TFE Classic (Lock 60fps)
STUBBED: load window icon in /home/user/SeriousSamClassic-VK/SamTFE/Sources/SeriousSam/MainWindow.cpp, line 172.
STUBBED: Need SDL invisible window or something in /home/user/SeriousSamClassic-VK/SamTFE/Sources/SeriousSam/MainWindow.cpp, line 353.
STUBBED: !!! FIXME: get the code back in from Ryan's original port. in /home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Stream.cpp, line 928.
STUBBED: Report actual SDL device name? in /home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Sound/SoundLibrary.cpp, line 269.
STUBBED: co-opt the existing T-buffer support for multisampling? in /home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Graphics/SDL/SDLOpenGL.cpp, line 113.
./run_game.sh: строка 13: 23434 Ошибка сегментирования                   "./SeriousSam"
```

**Comment by tx00100xt** [comment]
Желательно взглянуть на лог сборки с патчем где-нибудь на [pastebin](https://pastebin.com/). 
И на лог игры при старте игры с vulkan, он тут: .local/share/Serious Engine/serioussam/SeriousSam.log
Информации из консоли явно недостаточно.

**Comment by tx00100xt** [comment]
Чтобы не использовать Timer.cpp из ptitSeb вот патч. (вложение [rpi4.patch.txt](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8822686/rpi4.patch.txt)). Если с ним соберется то сделаю commit.
Понять что не так с первым патчем можно только увидел лог сборки. Не забываем указывать -DRPI4=TRUE при сборке

**Comment by xboxones1** [comment]
Нет с этим патчем тоже не собирается. Не знаю в чем дело но лога там нет, его нигде нет. При сборке скопировал: 
```
[ 46%] Building CXX object CMakeFiles/Engine.dir/Engine/Base/Timer.cpp.o
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Timer.cpp:97:4: error: #error Please implement for your platform/compiler.
   97 |   #error Please implement for your platform/compiler.
      |    ^~~~~
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Timer.cpp:146:6: error: #error "Unsupported compiler"
  146 | #    error "Unsupported compiler"
      |      ^~~~~
[ 47%] Building CXX object CMakeFiles/Entities.dir/Entities/Pendulum.cpp.o
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Timer.cpp: In function ‘__int64 ReadTSC()’:
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Timer.cpp:99:1: warning: no return statement in function returning non-void [-Wreturn-type]
   99 | }
      | ^
[ 47%] Building CXX object CMakeFiles/Entities.dir/Entities/Pipebomb.cpp.o
make[2]: *** [CMakeFiles/Engine.dir/build.make:539: CMakeFiles/Engine.dir/Engine/Base/Timer.cpp.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…
[ 47%] Building CXX object CMakeFiles/Entities.dir/Entities/PlayerActionMarker.cpp.o
make[1]: *** [CMakeFiles/Makefile2:261: CMakeFiles/Engine.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…


```

**Comment by xboxones1** [comment]
Вот логи запуска с подмененным Timer.cpp
[gdb.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8823377/gdb.log)
[SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8823380/SeriousSam.log)

**Comment by xboxones1** [comment]
С первым патчем ошибка:
```
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Timer.cpp: In function ‘void cpu_rdtsc(uint64_t*)’:
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Timer.cpp:164:25: error: ‘сс’ was not declared in this scope
  164 |     *result = (uint64_t)сс;
      |                         ^~
make[2]: *** [CMakeFiles/Engine.dir/build.make:539: CMakeFiles/Engine.dir/Engine/Base/Timer.cpp.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…
[ 46%] Building CXX object CMakeFiles/Entities.dir/Entities/ModelHolder.cpp.o
[ 46%] Building CXX object CMakeFiles/Entities.dir/Entities/MovingBrush.cpp.o
make[1]: *** [CMakeFiles/Makefile2:261: CMakeFiles/Engine.dir/all] Ошибка 2
make[1]: *** Ожидание завершения заданий…
```
Он скорее всего актуален для armhf.

Со вторым собралось без проблем, но опять же вываливается в Ошибку сегментирования

**Comment by tx00100xt** [comment]
Лучше бы конечно с первым патчем.
Компилятор ругается что "cc" вне зоне видимости
можно закомментировать её "//volatile unsigned cc;" в двух местах ниже строки "// TODO: Raspberry PI 4" и прописать ее в начале файла где-нибудь на 40,41 строке.

А сегфолт происходит, потому что vulkan не запускается, и идет попытка запуска в режиме OpenGL
 с неправильным созданием окна для OpenGL
>Vulkan: Suitable physical device is present.
Vulkan error: Can't create VkDevice.
Vulkan error: Init Driver Vulkan Error!
Нельзя установить требуемый режим дисплея!
>
>Trying recovery mode 0...
  Starting display mode: 640x480xdesktop (Оконный режим)
Multimonitor is not supported on this platform.
SDL: CreateWindow with flag (SDL_WINDOW_VULKAN) Done.
OpenGL context creation: The specified window isn't an OpenGL window
>
Это я профиксирую, а вот почему не создаётся VkDevice, это уже другой вопрос

**Comment by tx00100xt** [comment]
>С первым патчем ошибка:
>
Ясно - сс написано по русски :). Я подсветил синтаксис и увидел что все сс на английском а
>    *result = (uint64_t)сс;
>
на русском. Да и такое бывает.

**Comment by xboxones1** [comment]
```
[ 41%] Building CXX object CMakeFiles/Entities.dir/Entities/Fishman.cpp.o
{стандартный ввод}: Сообщения ассемблера:
{стандартный ввод}:106: Ошибка: неизвестная мнемоника «mcr» — «mcr p15,0,x2,c9,c12,2»
{стандартный ввод}:113: Ошибка: неизвестная мнемоника «mcr» — «mcr p15,0,x3,c9,c12,0»
{стандартный ввод}:117: Ошибка: неизвестная мнемоника «mcr» — «mcr p15,0,x2,c9,c12,1»
{стандартный ввод}:128: Ошибка: неизвестная мнемоника «mrc» — «mrc p15,0,x1,c9,c13,0»
{стандартный ввод}:1003: Ошибка: неизвестная мнемоника «mcr» — «mcr p15,0,x1,c9,c12,2»
{стандартный ввод}:1010: Ошибка: неизвестная мнемоника «mcr» — «mcr p15,0,x2,c9,c12,0»
{стандартный ввод}:1014: Ошибка: неизвестная мнемоника «mcr» — «mcr p15,0,x1,c9,c12,1»
{стандартный ввод}:1025: Ошибка: неизвестная мнемоника «mrc» — «mrc p15,0,x0,c9,c13,0»
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Stream.cpp: In member function ‘virtual void CTFileStream::Read_t(void*, SLONG)’:
/home/user/SeriousSamClassic-VK/SamTFE/Sources/Engine/Base/Stream.cpp:1040:8: warning: ignoring return value of ‘size_t fread(void*, size_t, size_t, FILE*)’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
 1040 |   fread(pvBuffer, slSize, 1, fstrm_pFile);
      |   ~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [CMakeFiles/Engine.dir/build.make:539: CMakeFiles/Engine.dir/Engine/Base/Timer.cpp.o] Ошибка 1
make[2]: *** Ожидание завершения заданий…

```

**Comment by xboxones1** [comment]
Да, теперь запускается, но на vulkan не переключается.

**Comment by tx00100xt** [comment]
Ошибка в логе
>Vulkan error: Init Driver Vulkan Error!
Нельзя установить требуемый режим дисплея!
>
вот здесь стопорится [vkCreateDevice](https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/SamTFE/Sources/Engine/Graphics/Gfx_Vulkan.cpp#L811)

Для того чтобы было больше информации нужно собрать с SVK_ENABLE_VALIDATION 1 и посмотреть что в логе игры.
Проще сделать так, в файле SamTFE/Sources/Engine/Graphics/Gfx_Vulkan.cpp заменить 
>#ifndef NDEBUG
  #define SVK_ENABLE_VALIDATION 1
#else
  #define SVK_ENABLE_VALIDATION 0
#endif // !NDEBUG
>
на
>#ifndef NDEBUG
  #define SVK_ENABLE_VALIDATION 1
#else
  #define SVK_ENABLE_VALIDATION 1
#endif // !NDEBUG
>
Пересобрать, запустить игру, а здесь прикрепить лог игры.

**Comment by xboxones1** [comment]
Вроде ничего нового.
[SeriousSam.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8825442/SeriousSam.log)
Vulkan точно работает,  при vkcube кубик крутится. 
Вывод vulkaninfo
[vulkan.txt](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8825469/vulkan.txt)

**Comment by tx00100xt** [comment]
Я добавил код для вывода ошибки при вызове vkCreateDevice https://github.com/tx00100xt/SeriousSamClassic-VK/commit/f92e991e22f58fe95f89b295e3e883d4cd60b699
Теперь в логе игры должна прописаться возвращаемая ошибка.

**Comment by xboxones1** [comment]
Вот логи:
[VALIDATION 0.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8828686/VALIDATION.0.log)
[VALIDATION 1.log](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8828687/VALIDATION.1.log)

**Comment by tx00100xt** [comment]
Из vulkan.txt видно, что установлены два драйвера
>	driverName         = llvmpipe
>	driverName         = V3DV Mesa
>
У меня тоже установлено два драйвера RADV и AMDVLK.
Я могу запустить SeriousSam с любым из них.
$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/radeon_icd.x86_64.json 
(RADV) 
или
$ VK_ICD_FILENAMES=/usr/share/vulkan/icd.d/amd_icd64.json 
(AMDVLK)
С обоими драйверами SeriousSam работает одинаково хорошо. В новой версии драйвера еще проще
> AMD_VULKAN_ICD=RADV или AMD_VULKAN_ICD=AMDVLK
>
Посмотреть какой драйвер запускается по дефолту можно просто
$ VK_INSTANCE_LAYERS=VK_LAYER_MESA_overlay vkcube
Mesa overlay покажет информацию.

Далее смотрим vulkan.txt и видим
>Device Extensions: count = 67
>
для llvmpipe
>Device Extensions: count = 44
>
для V3DV Mesa

Смотрим VALIDATION.0.log или VALIDATION.1.log
>Vulkan: --- found 44 device extensions ---
>
Делаем вывод что выбрался V3DV Mesa

Смотрим ошибку VkCreateDevice в VALIDATION.0.log или VALIDATION.1.log
>Vulkan error: VK_ERROR_FEATURE_NOT_PRESENT!
>
https://www.khronos.org/registry/vulkan/specs/1.3-extensions/man/html/vkCreateDevice.html#_description
> If any requested feature is not supported, vkCreateDevice must return VK_ERROR_FEATURE_NOT_PRESENT
> Support for features can be checked by querying vkGetPhysicalDeviceFeatures.
>
Смотрим SvkUtils.cpp, BOOL SvkMain::PickPhysicalDevice()
Видим вызов vkGetPhysicalDeviceFeatures(physDevice, &gl_VkPhFeatures);
Устройств два, VALIDATION.0.log
>Vulkan: Physical Devices Count: 2
>

Потом видим что глобальная структура gl_VkPhFeatures не используется в Gfx_Vulkan.cpp vkCreateDevice
а видим фиксированные 
>  VkPhysicalDeviceFeatures features = {};
>  features.samplerAnisotropy = VK_TRUE;
>  features.depthBounds = VK_TRUE;
>

>  createInfo.pEnabledFeatures = &features;
>
 
Смотрим опять vulkan.txt
для llvmpipe
>VkPhysicalDeviceFeatures:
>	samplerAnisotropy                       = true
>   depthBounds                             = false
>

для V3DV Mesa
>VkPhysicalDeviceFeatures:
>	samplerAnisotropy                       = true
>   depthBounds                             = false
>

Решение:
Первое(универсальное) - создать структуру VkDeviceCreateInfo createInfo с использованием gl_VkPhFeatures, тут следует учесть количество Device, и немного переписать код.
Второе - прописать VkPhysicalDeviceFeatures для Rsperry Pi из vulkaminfo для V3DV.

Первый вариант я сделаю попозже, когда появиться время. Патч для второго варианта приложен.
Думаю теперь vkCreateDevice отработает корректно.
[rpi4_vilkan_features.patch.txt](https://github.com/tx00100xt/SeriousSamClassic-VK/files/8839446/rpi4_vilkan_features.patch.txt)

**Comment by xboxones1** [comment]
Vulkan заработал, но производительноть куда хуже чем на OpenGL. Я думал будет наоборот куда веселее, но в любом случае круто.

**Comment by tx00100xt** [comment]
По разному бывает. Конкретно у меня на встройке Vega7 на windows тоже медленней, а на linux одинаково, что vulkan - что opengl. А кто-то в теме linux.org.ru написал что на rx580 vulkan у него гораздо быстрей чем opengl на SeriousSam.

Я пока не буду закрывать issue, когда доделаю нормальное определение VkPhysicalDeviceFeatures - закрою

**Comment by tx00100xt** [comment]
Готово, сделал универсальный вариант https://github.com/tx00100xt/SeriousSamClassic-VK/commit/40bfc9a0cebc5a49a371d99d1164502f2de28b7f
