### ISSUE TITLE
Fullscreen в Vulkan работает некорректно

### ISSUE THREAD

**Issue by vlad54rus** [tx00100xt/SeriousSamClassic-VK#33]
1. Не получает эксклюзивный режим (PresentMon рапортует режим презентации как Composed GPU Copy/Composed Flip, а должен быть Legacy Flip/Independent Flip). Из-за этого инпут-лаг выше.
2. Смена разрешения не работает, игра просто остаётся висеть в окне меньшего размера.

В OpenGL всё работает корректно.
![Снимок экрана (41)](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/22005398/b8cf77fb-6f44-4e1e-ae64-26ec3f7d3953)

**Comment by tx00100xt** [comment]
Очень редко запускаю Windiws. Я почему-то думал что там всё в порядке. В Linux при любом разрешении выставляется полноэкранный режим. Я сделал билд для Windows, где при разрешении отличным от десктопа всё равно выставляется полноэкранный режим. Архив прикреплен к сообщению. Если всё в порядке, я сделаю коммит с соответствующим изменением кода.

По поводу эксклюзивного полноэкранного режима у меня пока что нет никаких планов.

[SeriousSamClassicVk-20231026-win64-bin.7z.zip](https://github.com/tx00100xt/SeriousSamClassic-VK/files/13177978/SeriousSamClassicVk-20231026-win64-bin.7z.zip)

**Comment by vlad54rus** [comment]
Да, теперь смена разрешения работает.

**Comment by tx00100xt** [comment]
Последний релиз обновил. 
Скачать можно здесь: https://github.com/tx00100xt/SeriousSamClassic-VK/releases 
или автобилд тут: https://github.com/tx00100xt/SeriousSamClassic-VK/actions/runs/6664072633#artifacts
