### ISSUE TITLE
validity check error arch aur

### ISSUE THREAD

**Issue by LethalManBoob** [tx00100xt/SeriousSamClassic-VK#34]
![image](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/30273211/7578495d-7962-4885-8b6d-59bc9210d8af)

**Comment by tx00100xt** [comment]
You need to download a new v1.10.6.tar.gz
To do this, delete the old archive:
```rm -v ~/.cache/pacaur/serioussam-vk/v1.10.6.tar.gz```
and run the installation again:
```pacaur -Syua serioussam-vk```

>LethalManBoob:
>And I dont want to keep on but is there anyway you can double the size of the weapon hud sprites so they dont get cut off in the hud? Its the last issue i have with this port
>
The size of weapon icons has been increased, you can choose a large or small size (in version serioussam-vk 1.10.6-3)
https://github.com/tx00100xt/SeriousSamClassic-VK/releases/tag/v1.10.6

All addons can now be installed using the meta package
https://bbs.archlinux.org/viewtopic.php?pid=2128189#p2128189
```pacaur -Syua serioussam-vk```
```pacaur -Sayu --needed --foreign --noedit serioussam-addons-meta```

**Comment by LethalManBoob** [comment]
Thank you this fixed it and big thanks for the icon fix. :) Presentation is much better now.
I would look at the grammar for the new settings btw. "is very small" would better be "very small"
