### ISSUE TITLE
Full screen stopped working v1.10.6

### ISSUE THREAD

**Issue by just-thefacts** [tx00100xt/SeriousSamClassic-VK#35]
No full screen works for me at all since the last update. Windows x64 version, Linux is fine. It also switches from Vulkan to OpenGL after is fails to change.

![no-fs](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/144458627/7682e2de-319e-43c4-841d-63fbaabe54dc)

**Comment by tx00100xt** [comment]
Try this version: https://github.com/tx00100xt/SeriousSamClassic-VK/actions/runs/6663904137#artifacts

If it works, I'll think about what can be done. Full screen mode works for me under Windows on Vulkan.

**Comment by just-thefacts** [comment]
That worked (TFE and TSE, Win64). Thanks again.

**Comment by tx00100xt** [comment]
Check out this build. If everything goes well, I will make a change to the repository code and update the release.
[SeriousSamClassicVk-20231029-win64-bin.7z.zip](https://github.com/tx00100xt/SeriousSamClassic-VK/files/13198699/SeriousSamClassicVk-20231029-win64-bin.7z.zip)

**Comment by just-thefacts** [comment]
@tx00100xt 20231029 worked perfectly. I switched it back and forth between 720p windowed and 1080p full screen. Looks good.

**Comment by tx00100xt** [comment]
> worked perfectly. I switched it back and forth between 720p windowed and 1080p full screen. Looks good

Fine. Then I'll add the code to the repository

**Comment by tx00100xt** [comment]
Release updated: https://github.com/tx00100xt/SeriousSamClassic-VK/releases

**Comment by just-thefacts** [comment]
New info: Full screen still does not work in OpenGL. Works in Vulkan now, but I was trying to test OpenGL vs Vulkan performance, etc. and could not. Just FYI.

**Comment by tx00100xt** [comment]
I think this is a problem with the drivers or some settings in the Windows system. For me and others, the full-screen mode of Vulkan and OpenGL worked before this.

You get an error when calling the Win32 ChangeDisplaySettings function:
https://github.com/tx00100xt/SeriousSamClassic-VK/blob/main/SamTFE/Sources/Engine/Graphics/Adapter.cpp#L511
The function is described here:
https://learn.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-changedisplaysettingsa

I just removed the call to this function for Vulkan if the resolution matches the display resolution. 
https://github.com/tx00100xt/SeriousSamClassic-VK/commit/9f66ce03da31290112d2ef2e923070c1afa75690

Borderless windowed mode would suit you. At the moment it is not in the code. Maybe I'll do it sometime in the future

**Comment by just-thefacts** [comment]
No idea then. It's just a standard Windows 22H2 install with a Radeon RX 6600, driver 23.10.2 and it worked fine a month or so ago on 1.10.5, and previously with the earlier release of 1.10.6, but not after updates were made to 1.10.6.

It's not a big deal to me, I'll just play on Linux and use the GOG version if I ever wanted to play on Windows I guess.

**Comment by tx00100xt** [comment]
Perhaps this build will have fullscreen mode in OpenGL too.
[SeriousSamClassicVk-20231031-win64-bin.7z.zip](https://github.com/tx00100xt/SeriousSamClassic-VK/files/13220696/SeriousSamClassicVk-20231031-win64-bin.7z.zip)

**Comment by just-thefacts** [comment]
That one works. Thanks.
