### ISSUE TITLE
Publish to Flathub

### ISSUE THREAD

**Issue by spazziale** [tx00100xt/SeriousSamClassic-VK#36]
Would be cool to have it in flathub

**Comment by tx00100xt** [comment]
The idea to host the game on flathub is a good one. I haven't created flatpack before. I'll try to study this process in my spare time.

**Comment by tx00100xt** [comment]
You can try the test build
```
flatpak install --user https://dl.flathub.org/build-repo/78911/io.itch.tx00100xt.SeriousSamClassic-VK.flatpakref
```
You need to copy all game data to a directory
```
~/.var/app/io.itch.tx00100xt.SeriousSamClassic-VK/data/Serious-Engine/serioussam
```
for The First Encounter, and
```
~/.var/app/io.itch.tx00100xt.SeriousSamClassic-VK/data/Serious-Engine/serioussamse
```
for The Second Encounter.

Launching games from the application launch menu.
The First Encounter can also be launched using the console command:
```
flatpak run  io.itch.tx00100xt.SeriousSamClassic-VK
```
Uninstall using the console command:
```
flatpak uninstall  io.itch.tx00100xt.SeriousSamClassic-VK
```

**Comment by tx00100xt** [comment]
Flatpack published:
https://flathub.org/en-GB/apps/io.itch.tx00100xt.SeriousSamClassic-VK

Description added to README.md
https://github.com/tx00100xt/SeriousSamClassic-VK#flatpak

**Comment by spazziale** [comment]
> Flatpak published: https://flathub.org/en-GB/apps/io.itch.tx00100xt.SeriousSamClassic-VK
> 
> Description added to README.md https://github.com/tx00100xt/SeriousSamClassic-VK#flatpak

loving it! Thanks!
![image](https://github.com/tx00100xt/SeriousSamClassic-VK/assets/46284310/86218a6d-61e1-41f5-b726-085f09607357)
