### ISSUE TITLE
Add an option to force screen refresh rate

### ISSUE THREAD

**Issue by Kappa971** [tx00100xt/SeriousSamClassic-VK#38]
Hi, I have an AMD RX 6700 XT GPU, Windows 11, the latest AMD drivers 24.8.1 and Serious Sam VK 32 bit (to use Creative ALchemy with an X-Fi).
Unfortunately, both in the original game and in your source port I can't set the correct screen refresh rate, the game in both OpenGL and Vulkan always chooses the lowest refresh rate supported by the screen for a given resolution (in my case 50 Hz for 1920x1080). There is a game command that indicates "RefreshRate" but it doesn't work and any value other than "0" causes the game to change graphics API and returning an error regarding the previous mode, so I can only play in 1920x1080 at 50 Hz (on a 144 Hz screen) 😅...
Currently it only works with the original game in Direct3D + dgvoodoo2 but obviously the performance would be better in OpenGL or Vulkan. I hope you can fix this annoying bug, thanks.

EDIT
It also works with this patch https://github.com/SamClassicPatch/SuperProject by setting borderless window in game options.

**Comment by just-thefacts** [comment]
persistent extern user INDEX gap_iRefreshRate=(INDEX)0;
persistent extern user INDEX sam_iMaxFPSActive=(INDEX)144;
persistent extern user INDEX sam_iMaxFPSInactive=(INDEX)60;

Those are the relevant settings (mine, not default) in the "PersistentSymbols.ini" though when I tried setting "gap_iRefreshRate" to 120 on a 144Hz monitor, it caused the game to fail to go into full screen, but maybe if you set it to match the actual refresh rate it will work? "0" = "default" in the menus. "120" was the max I could select in the menu, if memory serves me. I get the feeling the game wants that setting to be "default/0" or match Windows setting.

Also, in "path to game.../Scripts/" edit the "Game_startup.ini" and any settings in that are "auto executed" on each game launch. Good place for custom settings. Of course, something may have changed since I tested this on Windows. I play on Linux.

**Comment by Kappa971** [comment]
> persistent extern user INDEX gap_iRefreshRate=(INDEX)0; persistent extern user INDEX sam_iMaxFPSActive=(INDEX)144; persistent extern user INDEX sam_iMaxFPSInactive=(INDEX)60;
> 
> Those are the relevant settings (mine, not default) in the "PersistentSymbols.ini" though when I tried setting "gap_iRefreshRate" to 120 on a 144Hz monitor, it caused the game to fail to go into full screen, but maybe if you set it to match the actual refresh rate it will work? "0" = "default" in the menus. "120" was the max I could select in the menu, if memory serves me. I get the feeling the game wants that setting to be "default/0" or match Windows setting.
> 
> Also, in "path to game.../Scripts/" edit the "Game_startup.ini" and any settings in that are "auto executed" on each game launch. Good place for custom settings. Of course, something may have changed since I tested this on Windows. I play on Linux.

The game is set by default like this:
```
persistent extern user INDEX gap_iRefreshRate=(INDEX)0;
persistent extern user INDEX sam_iMaxFPSActive=(INDEX)500;
persistent extern user INDEX sam_iMaxFPSInactive=(INDEX)10;
```

I just tried to edit `gap_iRefreshRate` from `0` to `144` but the game doesn't like it and when the game starts it will set the resolution to 640x480 in Direct3D. I don't know what the other two commands do but I doubt they will help.

As written above, now I'm using the Classic Patch which allows to set the screen to borderless windowed mode, this way the game doesn't mess with the refresh rates and uses the one set on Windows. It isn't the definitive solution but it works.

Maybe this bug could be permanently fixed in a source port like this (along with the font scaling in NETRICSA that the Classic Patch has).

**Comment by just-thefacts** [comment]
Yeah, I am not sure why the "gap_iRefreshRate" setting is so picky, but mine, on Linux, when set to default, or "0", runs at the monitor's rate of 144. Not sure on Windows, I avoid it when I can. 50 Hz/FPS would make me nuts. I can't take frame rates/refresh rates under 120 after getting used to a 144Hz monitor.

gap_iRefreshRate= monitor refresh rate. Not sure why this setting would exist.
sam_iMaxFPSActive= maximum in game frame rate. useful to cap frame rate a bit below refresh rate to avoid tearing.
sam_iMaxFPSInactive= max frame rate when minimized, not the focus, or behind another window I presume.

**Comment by Kappa971** [comment]
After updating Windows 11 to 24H2 and AMD drivers to 24.10.1, Serious Sam Classic is back to running properly at 144Hz in OpenGL. I don't know why but it's fine. Hopefully it won't break again in the future.
