### ISSUE TITLE
Add borderless windowed mode

### ISSUE THREAD

**Issue by Kappa971** [tx00100xt/SeriousSamClassic-VK#40]
A workaround to prevent the game from setting the minimum screen refresh rate for a given resolution in OpenGL and Vulkan.

An alternative solution (and probably simpler to implement) to https://github.com/tx00100xt/SeriousSamClassic-VK/issues/38, waiting for an option to specify the desired refresh rate.

**Comment by tx00100xt** [comment]
https://github.com/tx00100xt/SeriousSamClassic-VK/releases/tag/1.10.7
