### ISSUE TITLE
is it possible to add SSAA or 16xmsaa?

### ISSUE THREAD

**Issue by LethalManBoob** [tx00100xt/SeriousSamClassic-VK#5]
To tackle alpha texture aliasing. Thanks. Its more noticable on the second encounter with is vegetation.

**Comment by tx00100xt** [comment]
>is it possible to add SSAA or 16xmsaa? #5
>
MSАA 16x - yes

**Comment by LethalManBoob** [comment]
Yeah it seems i only support up to 8xmsaa. I presume nothing can be done since I am on an nvidia 3070

**Comment by tx00100xt** [comment]
8x msaa is normal. 16x msaa is present in intel UHD graphics. It seems to be.
I recommend improving the quality of the game using the game settings in Video -> Rendering and Advanced Options.
