### ISSUE TITLE
In-game console not opening

### ISSUE THREAD

**Issue by eFeTRn** [tx00100xt/SeriousSamClassic-VK#7]
Hi, i downloaded the glibc-2.35 binary version from releases tab but i can't open console by pressing the tilde key.

**Comment by tx00100xt** [comment]
Hello.
I found that the archive SeriousSamClassicVK_v1.10.2-glibc-2.35-bin.tar.xz contains old files. 
That's my mistake. I updated the file in release. 

Regarding the console - it opens only in the English layout.

**Comment by eFeTRn** [comment]
Thanks for the reply.
