### ISSUE TITLE
Second Encounter not launching (glibc 2.35 latest binary)

### ISSUE THREAD

**Issue by eFeTRn** [tx00100xt/SeriousSamClassic-VK#8]
libGame.so: cannot open shared object file: No such file or directory

**Comment by eFeTRn** [comment]
Edit: I fixed it by copying First Encounter's libgame.so to Second Encounter's executeable directory

**Comment by tx00100xt** [comment]
> Edit: I fixed it by copying First Encounter's libgame.so to Second Encounter's executeable directory
>
This is the wrong decision. Libraries in TSE Must be libgameMP.so and libEntitiesMP.so
It is necessary to create the ModEXT.txt file in the root directory of the TSE game, if it does not exist. And write two letters in it: MP
